### PR TITLE
fix for #59

### LINKED ISSUE #59: wrong language detected
The github linguist thinks that your .mo files are written in the language Modelica,
see https://github.com/github/linguist/issues/2486
This could be fixed in two ways: you could change the extension from .mo to something else or you could add a `.gitattributes` file containing following line:
`*.mo linguist-language=Markdown`

If you want, I can send a Pull Request.

### PR DESCRIPTION
**Pull request by thorade**
Use a .gitattributes file to tell the github linguist explicitly, that in this repo all *.mo files are written in Markdown.
This fixes #59

### CODE REVIEW

**Comment by mosesn** [comment]
@thorade is the expectation that github should be able to render these pages properly after this patch?  from https://github.com/thorade/effectivescala/blob/master/effectivescala.mo it looks like it still can't.

**Comment by thorade** [comment]
Yes, that is one expectation. In order to render correctly, one would also need to add PEG markdown to the list of known languages for github linguist:
https://github.com/github/linguist/blob/master/lib/linguist/languages.yml
Also, the percentage of used languages in the language breakdown bar changes.

Second expectation is to get this repo out of this list:
https://github.com/trending?l=modelica

**Comment by thorade** [comment]
PS: github linguist uses textmate grammars or atom grammars for syntax highlighting, so if you have a grammar file for PEG markdown, adding that language to github linguist would be easy.

**Comment by mariusae** [comment]
Thanks!

**Pull request merged**
