### PR TITLE
Update link to cake pattern

### PR DESCRIPTION
**Pull request by jimschubert**
The blog's route was updated to not include the date.

Now: http://jonasboner.com/real-world-scala-dependency-injection-di/

### CODE REVIEW

**Comment by mosesn** [comment]
LGTM

**Comment by mosesn** [comment]
Actually, do you mind fixing the link in the translations too?

**Comment by jimschubert** [comment]
@mosesn Sorry, I edited directly on GitHub and didn't consider there were links in translations.

I've updated all occurrences of the link squashed.

**Comment by mosesn** [comment]
no worries!  LGTM

**Comment by mosesn** [comment]
@mariusae can you take a look?

**Comment by mariusae** [comment]
Thanks!

**Pull request merged**
